# Default values for Go projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repo: gcr.io/jenkinsxio/jx-app-sonar-scanner
  tag: latest
sqServer: "{{ .Values.sqServer }}"
apiKey: "{{ .Values.apiKey }}"
scanonpreview: "{{ .Values.scanonpreview }}"
scanonrelease: "{{ .Values.scanonrelease }}"
